# Generated by Django 5.1.5 on 2025-02-01 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creer_compte', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totale_point', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Identification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.déshets')),
                ('pseudo_G', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creer_compte.greeneur')),
            ],
        ),
    ]
