# Generated by Django 5.1.5 on 2025-02-01 19:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composteur',
            fields=[
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('NB_GSM', models.CharField(max_length=100, null=True)),
                ('pseudo_C', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('e_mail', models.EmailField(max_length=100, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('lat', models.CharField(max_length=100, null=True)),
                ('lng', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('Validation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Greeneur',
            fields=[
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('NB_GSM', models.CharField(max_length=100, null=True)),
                ('pseudo_G', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('e_mail', models.EmailField(max_length=100, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('lat', models.CharField(max_length=100, null=True)),
                ('lng', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('portfeuille', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pseudo_C', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creer_compte.composteur')),
            ],
        ),
    ]
