# Generated by Django 5.1.5 on 2025-02-01 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creer_compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Déshets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animaux', models.DecimalField(decimal_places=2, max_digits=10)),
                ('azoté', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carboné', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_disponible', models.DateField()),
                ('heure_disponible', models.TimeField()),
                ('totale_point', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('valider', models.BooleanField(default=False)),
                ('pseudo_C', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creer_compte.composteur')),
                ('pseudo_G', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creer_compte.greeneur')),
            ],
        ),
    ]
